name: momo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  dio: ^4.0.4
  dio_http_cache: ^0.3.0
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.13
  velocity_x: ^3.4.0
  webview_flutter: ^3.0.1
  flutter_application_id: ^2.0.0-dev
  google_fonts: ^2.3.1
  json_annotation: ^4.1.0
  json_serializable: ^4.1.4
  intl: ^0.17.0
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^1.0.3
  pin_code_fields: ^7.4.0
  flutter_screenutil: ^5.4.0+1
  timeago: ^3.2.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  readmore: ^2.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/momo.png"
flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/navigator/
    - assets/flag/
    - assets/reactions/
    - assets/momo/
  uses-material-design: true
